name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hey First Action completed!"
      - name: Print goodbye
        run: echo "GoodBye"
